name: Test

on: push

jobs:
  main:
    runs-on: self-hosted
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run
        run: |
          /Users/eugene/Work/run-agent/run-agent <<'EOF'
          ls
          pwd
          uname
          EOF


