name: Test

on: push

jobs:
  main:
    runs-on: self-hosted
    
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Run
        run: |
          "$RUNNER_TOOLS_PATH"/run-agent gh-debian-11-arm <<'EOF'
          ls
          pwd
          uname
          EOF
        


