name: Test

on: push

jobs:
  main:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Connect
        run: |
          sudo apt install wireguard
          cat > wg.conf << EOF
          [Interface]
          PrivateKey = ${{ secrets.WG_PRIVATE_KEY }}

          [Peer]
          PublicKey = ${{ secrets.WG_SERVER_PUBLIC_KEY }}
          PresharedKey = ${{ secrets.WG_SERVER_PRESHARED_KEY }}
          AllowedIPs = 10.8.0.0/24, 192.168.1.0/24
          Endpoint = server.gershnik.info:52320
          EOF
          sudo ip link add dev wg0 type wireguard
          sudo ip address add dev wg0 10.8.0.3 peer 10.8.0.1
          sudo wg setconf wg0 wg.conf
          sudo ip link set up dev wg0
          sudo ip route add 192.168.1.0/24 dev wg0
          sudo resolvectl dns wg0 192.168.1.1
          ./script

