name: Test

on: push

jobs:
  main:
    runs-on: self-hosted
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run
        run: |
          "$RUN_AGENT_PATH" gh-debian-11 15 <<'EOF'
          ls
          pwd
          uname
          EOF
        


